### PR TITLE
Add test for FCGI over unix domain socket

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Looks good, thanks!  It's a bit embarassing that there were no tests :)

**Comment by karenetheridge** [comment]
I'm probably going to revert this. The tests aren't passing on MSWin32, and FCGI::Client uses Any::Moose, which is not something I think we should be reintroducing into people's dependency chains.

**Comment by michal-josef-spacek** [comment]
@karenetheridge In FCGI::Client 0.09 was switch to Moo (instead of Any::Moose). So I am proposing to add dependency to 0.09 version of FCGI::Client.

**Comment by michal-josef-spacek** [comment]
@karenetheridge I created issue for unix socket on Windows (https://rt.cpan.org/Ticket/Display.html?id=138057). I will prepare PR for it.

**Comment by michal-josef-spacek** [comment]
@karenetheridge https://github.com/perl-catalyst/FCGI/pull/7 and https://github.com/perl-catalyst/FCGI/pull/8

**Pull request merged**
